export const projectsData = [
  {
    slug: 'mirador-river-city',
    name: 'Mirador at River City',
    location: 'Jacksonville, FL',
    type: 'Roofing',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'In Progress',
    client: 'Olympus Property',
    img: '/images/mirador.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'providence-trail',
    name: 'Providence Trail',
    location: 'Nashville, TN',
    type: 'Paint and Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'In Progress',
    client: 'BR Providence Nashville, LLC',
    img: '/images/providence-trail.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'trails-at-bartram-park',
    name: 'Trails at Bartram Park',
    location: 'Jacksonville, FL',
    type: 'Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'In Progress',
    client: 'BH MANAGEMENT',
    img: '/images/trails-bartram.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'oasis-at-shingle-creek',
    name: 'Oasis at Shingle Creek',
    location: 'Kissimmee, FL',
    type: 'TBD',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'In Progress',
    client: 'TBD',
    img: '/images/roofing.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'lynn-university-garage',
    name: 'Lynn University Garage',
    location: 'Boca Raton, FL',
    type: 'New Construction',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'In Progress',
    client: 'Lynn University',
    img: '/images/new-construction.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'lakes-at-north-port',
    name: 'Lakes at North Port',
    location: 'North Port, FL',
    type: 'Windows and Trim',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2025',
    client: 'BH MANAGEMENT',
    img: '/images/lakes-north-port.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'polo-glen-apartment-homes',
    name: 'Polo Glen Apartment Homes',
    location: 'Rockledge, FL',
    type: 'Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/polo-glen.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'the-braxton',
    name: 'The Braxton',
    location: 'Palm Bay, FL',
    type: 'New Construction',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2025',
    client: 'American Landmark',
    img: '/images/braxton.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'oaks-of-woodland-park-apartments',
    name: 'Oaks of Woodland Park Apartments',
    location: 'Tampa, FL',
    type: 'Roofing',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2020',
    client: 'BH MANAGEMENT',
    img: '/images/oaks-woodland.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'lumi-hyde-park',
    name: 'Lumi Hyde Park',
    location: 'Tampa, FL',
    type: 'Paint and Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'Greystone & Co',
    img: '/images/lumi-hyde.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'the-avant-at-pembroke-pines',
    name: 'The Avant at Pembroke Pines',
    location: 'Pembroke Pines, FL',
    type: 'Roofing',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: 'TBD',
    client: 'BH MANAGEMENT',
    img: '/images/avant-pembroke.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'marcus-point-grande-apartment-homes',
    name: 'Marcus Point Grande Apartment Homes',
    location: 'Pensacola, FL',
    type: 'Multi-building',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2021',
    client: 'BH MANAGEMENT',
    img: '/images/marcus-point.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'timucuan-lakeside-at-town-center-apartments',
    name: 'Timucuan Lakeside at Town Center Apartments',
    location: 'Jacksonville, FL',
    type: 'Multi-building',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Bell Partners',
    img: '/images/timucuan.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'bleeker-hyde-park',
    name: 'Bleeker Hyde Park',
    location: 'Tampa, FL',
    type: 'Paint and Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Conti Capital',
    img: '/images/bleeker.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'sawgrass-creek-apartments',
    name: 'Sawgrass Creek Apartments',
    location: 'New Port Richey, FL',
    type: 'Paint and Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Cushman & Wakefield',
    img: '/images/sawgrass-creek.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'marisol-vista-apartment-homes',
    name: 'Marisol Vista Apartment Homes',
    location: 'St. Petersburg, FL',
    type: 'Siding and Paint',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/marisol-vista.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'reunion-crossing-townhomes',
    name: 'Reunion Crossing Townhomes',
    location: 'Kissimmee, FL',
    type: 'Interiors',
    scope: 'TBD',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/reunion-crossing.jpg',
    challenges: '',
    solutions: '',
  },
]

export function getProjects() { return projectsData }
export function getProjectBySlug(slug: string) { return projectsData.find(p => p.slug === slug) }
