export const projectsData = [
  {
    slug: 'lakes-at-north-port',
    name: 'Lakes at North Port',
    location: 'North Port, FL',
    type: 'Windows and Trim',
    scope: 'Window and exterior trim replacement',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2025',
    client: 'BH MANAGEMENT',
    img: '/images/lakes-north-port.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'polo-glen-reroof-2026',
    name: 'Polo Glen Apartment Homes',
    location: 'Rockledge, FL',
    type: 'Roofing',
    scope: 'Full reroof: buildings 12, 13, 15, 18, clubhouse & tennis structures',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2026',
    client: 'BH Management',
    img: '/images/polo-glen.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'polo-glen-apartment-homes',
    name: 'Polo Glen Apartment Homes',
    location: 'Rockledge, FL',
    type: 'Interiors',
    scope: 'Interior renovation',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/polo-glen.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'the-braxton',
    name: 'The Braxton',
    location: 'Palm Bay, FL',
    type: 'New Construction',
    scope: 'New construction',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2025',
    client: 'American Landmark',
    img: '/images/braxton.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'oaks-of-woodland-park-apartments',
    name: 'Oaks of Woodland Park Apartments',
    location: 'Tampa, FL',
    type: 'Roofing',
    scope: 'Roof replacement',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2020',
    client: 'BH MANAGEMENT',
    img: '/images/oaks-woodland.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'lumi-hyde-park',
    name: 'Lumi Hyde Park',
    location: 'Tampa, FL',
    type: 'Paint and Interiors',
    scope: 'Interior painting and finishes',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'Greystone & Co',
    img: '/images/lumi-hyde.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'the-avant-at-pembroke-pines',
    name: 'The Avant at Pembroke Pines',
    location: 'Pembroke Pines, FL',
    type: 'Roofing',
    scope: 'Roof replacement',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2023',
    client: 'BH MANAGEMENT',
    img: '/images/avant-pembroke.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'marcus-point-grande-apartment-homes',
    name: 'Marcus Point Grande Apartment Homes',
    location: 'Pensacola, FL',
    type: 'Multi-building',
    scope: 'Multi-building renovation',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2021',
    client: 'BH MANAGEMENT',
    img: '/images/marcus-point.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'timucuan-lakeside-at-town-center-apartments',
    name: 'Timucuan Lakeside at Town Center Apartments',
    location: 'Jacksonville, FL',
    type: 'Multi-building',
    scope: 'Multi-building renovation',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Bell Partners',
    img: '/images/timucuan.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'bleeker-hyde-park',
    name: 'Bleeker Hyde Park',
    location: 'Tampa, FL',
    type: 'Paint and Interiors',
    scope: 'Interior painting and finishes',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Conti Capital',
    img: '/images/bleeker.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'sawgrass-creek-apartments',
    name: 'Sawgrass Creek Apartments',
    location: 'New Port Richey, FL',
    type: 'Paint and Interiors',
    scope: 'Interior painting and finishes',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2022',
    client: 'Cushman & Wakefield',
    img: '/images/sawgrass-creek.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'marisol-vista-apartment-homes',
    name: 'Marisol Vista Apartment Homes',
    location: 'St. Petersburg, FL',
    type: 'Siding and Paint',
    scope: 'Siding and exterior painting',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/marisol-vista.jpg',
    challenges: '',
    solutions: '',
  },
  {
    slug: 'reunion-crossing-townhomes',
    name: 'Reunion Crossing Townhomes',
    location: 'Kissimmee, FL',
    type: 'Interiors',
    scope: 'Interior renovation',
    budget: 'TBD',
    timeline: 'TBD',
    completed: '2024',
    client: 'BH MANAGEMENT',
    img: '/images/reunion-crossing.jpg',
    challenges: '',
    solutions: '',
  },
]

export function getProjects() { return projectsData }
export function getProjectBySlug(slug: string) { return projectsData.find(p => p.slug === slug) }
